Use task errors when listing failing tasks
mozilla/mozci pull request #571
Opened 2021-12-01 10:36 UTC by La0

Closes #563 

The current `failing_tasks` algorithm only uses completed tasks with results: this totally skips the failed tasks with errors.

I made a bunch of changes here:
- `failing_tasks` now also checks if the task has any error
- task errors are loaded at the same time than task results
- missing test results are marked as failed
- fixed a bug on the task errors output (validx was not OK with current implementation)

2021-12-01 10:38 UTC, La0 commented
And [here](https://gist.github.com/La0/9758c0c42723d342d436fa9558bbb250) is the output for the push mentionned in the issue

2021-12-02 09:52 UTC, marco-c commented
> And [here](https://gist.github.com/La0/9758c0c42723d342d436fa9558bbb250) is the output for the push mentionned in the issue

There are still some intermittent groups without tasks associated to them, e.g. `"testing/web-platform/tests/css/css-counter-styles/oriya": [],`.

2021-12-02 09:59 UTC, marco-c commented on mozci/data/sources/artifact/__init__.py
> +                self.TASK_GROUPS[task_id][group] = False
We shouldn't assume that a missing result means a failing test, in most cases if a group is missing it means it didn't run at all.

2021-12-02 10:04 UTC, marco-c commented on mozci/task.py
> +            or len(task.errors) > 0
For example, OVuTZ20wTxa60Rd29DcfLA failed.
The test that failed was browser/base/content/test/general/browser_save_video_frame.js, belonging to group "browser/base/content/test/general/browser.ini".
The error is the last line of https://firefoxci.taskcluster-artifacts.net/OVuTZ20wTxa60Rd29DcfLA/0/public/test_info/mochitest-browser-chrome_errorsummary.log, and it isn't clear from the data which group the error belongs to.
If we applied this change, we would consider all groups in OVuTZ20wTxa60Rd29DcfLA as failing, even though actually only one of them failed.

2021-12-02 10:04 UTC, marco-c commented on mozci/data/sources/artifact/__init__.py
> +                self.TASK_GROUPS[task_id][group] = False
Same reasoning as https://github.com/mozilla/mozci/pull/571#discussion_r760937698

2021-12-03 18:34 UTC, ahal requested changes
Generally looks good but Marco's comment needs to be fixed, so removing from my queue.

2021-12-10 08:20 UTC, La0 commented
Not the right approach, closing

2021-12-10 08:20 UTC, closed without merging