Ignore errors for `try` pushes (Fixes  #587)
mozilla/mozci pull request #588
Opened 2021-12-23 19:02 UTC by chichi012

Fixes  #587 

Skipped error logs for pushes on the `try` branch.

2021-12-23 19:49 UTC, chichi012 commented
@marco-c  @jmaher if you have some time, kindly help review this pr

2021-12-23 20:01 UTC, jmaher commented
overall, I have no problem with this- I will let @marco-c determine if this is the right fix or if there is something else to do.

2021-12-24 15:07 UTC, marco-c commented
Instead of doing something specific for try, we could turn the error into a warning or a debug message. Wdyt @ahal?

2022-01-03 20:55 UTC, ahal commented
Yeah, this error is much more verbose for try pushes since the parent is typically a mozilla-central push. Maybe we could make it a `debug` message for try and a `warning` otherwise?

2022-01-03 20:56 UTC, ahal commented
Though if you think it could just be a debug message everywhere, that's fine with me.

2022-01-03 21:00 UTC, ahal requested changes

2022-01-03 21:00 UTC, ahal commented on mozci/data/sources/artifact/__init__.py
> +                logger.error(
Let's turn this into a `warning` message for the not try case.

2022-01-03 21:00 UTC, ahal commented on mozci/data/sources/artifact/__init__.py
> +                )
We should continue to at least log this at the `debug` level for try pushes. According to [the loguru docs](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.log) you should be able to do something like `logger.log(LEVEL, msg)` (where LEVEL is "DEBUG" or "WARNING").

2022-01-05 14:57 UTC, jmaher approved these changes

2022-01-05 15:32 UTC, merged